/*
 * This Kotlin source file was generated by the Gradle 'init' task.
 */
package demo.gradle.dependabot

class App {
    val message: String
        get() {
            return "Hello GitHub!!!!!!"
        }
}

fun main() {
    println(App().greeting)
}
